name: Build and Release

on:
  push:
    branches:
      - develop

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' 

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Get version and Minecraft info
        id: package-info
        run: |
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
          echo "minecraft=$(node -p "require('./package.json').minecraft")" >> $GITHUB_OUTPUT

      - name: Create Release
        if: success()
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.package-info.outputs.version }}
          release_name: Release v${{ steps.package-info.outputs.version }} for Minecraft ${{ steps.package-info.outputs.minecraft }}
          body: |
            Release for @sanctumterra/client v${{ steps.package-info.outputs.version }}
            Compatible with Minecraft ${{ steps.package-info.outputs.minecraft }}
          draft: false
          prerelease: false
